server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/love_keeper?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc:
          time_zone: Asia/Seoul
        default_batch_fetch_size: 1000
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET}

cloud:
  aws:
    credentials:
      access-key: ${PROD_AWS_ACCESS_KEY}
      secret-key: ${PROD_AWS_SECRET_KEY}
    s3:
      bucket: ${PROD_AWS_S3_BUCKET}
    region:
      static: ap-northeast-2
    stack:
      auto: false

fcm:
  certification: firebase-service-account.json

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    com.example.lovekeeper: debug