spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dev-db-server:3306/lovekeeper?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: dev_user
    password: dev_password

  mail:
    host: smtp.gmail.com
    port: 587
    username: lovekeepercompany@gmail.com
    password: ntxp wthn ekem zmkh
    properties.mail.smtp:
      auth: true
      starttls.enable: true

jwt:
  secret: sdfsjdfkjwlefkjwofidjsovijasodvmxcvmasidgjosaidjfoiwjeoiqjt
  access-token-validity-in-milliseconds: 3600000      # 1시간
  refresh-token-validity-in-milliseconds: 604800000   # 7일

server:
  port: 8081
