spring:
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        jdbc:
          time_zone: Asia/Seoul
        default_batch_fetch_size: 1000
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: lovekeepercompany@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

jwt:
  secret: ${JWT_SECRET}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: love-keeper
    region:
      static: ap-northeast-2
    stack:
      auto: false

fcm:
  certification: firebase-service-account.json

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type: info
    com.example.lovekeeper: info

server:
  port: ${PORT:8080}
  servlet:
    context-path: /
  error:
    include-exception: false
    include-stacktrace: never
    whitelabel:
      enabled: false