spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/love_keeper?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ehdfprl77

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create
        default_batch_fetch_size: 1000

  mail:
    host: smtp.gmail.com
    port: 587
    username: lovekeepercompany@gmail.com
    password: ntxp wthn ekem zmkh
    properties.mail.smtp:
      auth: true
      starttls.enable: true

jwt:
  secret: sdfsjdfkjwlefkjwofidjsovijasodvmxcvmasidgjosaidjfoiwjeoiqjt
  access-token-validity-in-milliseconds: 3600000      # 1시간
  refresh-token-validity-in-milliseconds: 604800000   # 7일