spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lovekeeper?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: ehdfprl77

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: lovekeepercompany@gmail.com
    password: ntxp wthn ekem zmkh
    properties.mail.smtp:
      auth: true
      starttls.enable: true

jwt:
  secret: "ZxC_v69nYJ7cRz2tK9WKkP4EL5f3Z0Up2MCaEGbFPGvf6fthNTpRnuBb8WJrEznB"
  access-token-validity-in-milliseconds: 3600000      # 1시간
  refresh-token-validity-in-milliseconds: 604800000   # 7일

server:
  port: 8080
